import { Clip, ClipComment, UserProfile } from './types';

export const MOCK_USERS: UserProfile[] = [
  {
    id: 'user-darshan-1',
    email: 'darshan@example.com',
    name: 'Darshan',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
    is_approved: true,
    created_at: '2026-09-01T10:00:00Z',
  },
  {
    id: 'user-rahul-2',
    email: 'rahul@example.com',
    name: 'Rahul',
    avatar_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80',
    is_approved: true,
    created_at: '2026-09-02T12:00:00Z',
  },
  {
    id: 'user-akash-3',
    email: 'akash@example.com',
    name: 'Akash',
    avatar_url: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=120&auto=format&fit=crop&q=80',
    is_approved: true,
    created_at: '2026-09-03T15:00:00Z',
  },
];

export const CURRENT_USER: UserProfile = MOCK_USERS[0];

export const INITIAL_MOCK_CLIPS: Clip[] = [
  {
    id: 'clip-1',
    youtube_video_id: 'dQw4w9WgXcQ',
    youtube_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    title: 'Ferrari sends it into turn 1 💀',
    description: 'Bro thought he was Verstappen on lap 1 in Singapore, absolute catastrophe',
    thumbnail_url: 'https://img.youtube.com/vi/dQw4w9WgXcQ/hqdefault.jpg',
    game: 'F1 24',
    category: 'Stupid/Funny',
    uploaded_by: 'user-darshan-1',
    uploader: {
      id: 'user-darshan-1',
      name: 'Darshan',
      avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
      email: 'darshan@example.com',
    },
    visibility: 'FRIENDS',
    tags: ['F1', 'Singapore', 'Crash', 'Ferrari', 'Funny'],
    reactions: [
      { emoji: '😂', count: 12, reactedByCurrentUser: true },
      { emoji: '💀', count: 8, reactedByCurrentUser: false },
      { emoji: '🔥', count: 4, reactedByCurrentUser: false },
      { emoji: '🤡', count: 3, reactedByCurrentUser: true },
    ],
    comments_count: 3,
    created_at: '2026-09-13T12:30:00Z',
    updated_at: '2026-09-13T12:30:00Z',
  },
  {
    id: 'clip-2',
    youtube_video_id: 'jNQXAC9IVRw',
    youtube_url: 'https://www.youtube.com/watch?v=jNQXAC9IVRw',
    title: '1v4 AWP retake on Mirage with 3 seconds left',
    description: 'My hands were shaking so hard I spilled my water immediately after defusing',
    thumbnail_url: 'https://img.youtube.com/vi/jNQXAC9IVRw/hqdefault.jpg',
    game: 'Counter-Strike 2',
    category: 'Clutch',
    uploaded_by: 'user-rahul-2',
    uploader: {
      id: 'user-rahul-2',
      name: 'Rahul',
      avatar_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80',
      email: 'rahul@example.com',
    },
    visibility: 'FRIENDS',
    tags: ['CS2', 'Mirage', 'AWP', 'Clutch', '1v4'],
    reactions: [
      { emoji: '🔥', count: 9, reactedByCurrentUser: true },
      { emoji: '💀', count: 5, reactedByCurrentUser: true },
      { emoji: '😂', count: 2, reactedByCurrentUser: false },
    ],
    comments_count: 2,
    created_at: '2026-09-12T18:45:00Z',
    updated_at: '2026-09-12T18:45:00Z',
  },
  {
    id: 'clip-3',
    youtube_video_id: '9bZkp7q19f0',
    youtube_url: 'https://www.youtube.com/watch?v=9bZkp7q19f0',
    title: 'Akash forgets push-to-talk is disabled for 20 minutes',
    description: 'The singing performance of a lifetime while trying to parallel park',
    thumbnail_url: 'https://img.youtube.com/vi/9bZkp7q19f0/hqdefault.jpg',
    game: 'Discord IRL',
    category: 'Voice/Discord',
    uploaded_by: 'user-akash-3',
    uploader: {
      id: 'user-akash-3',
      name: 'Akash',
      avatar_url: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=120&auto=format&fit=crop&q=80',
      email: 'akash@example.com',
    },
    visibility: 'FRIENDS',
    tags: ['Discord', 'IRL', 'Singing', 'MicFail'],
    reactions: [
      { emoji: '😂', count: 18, reactedByCurrentUser: true },
      { emoji: '💀', count: 14, reactedByCurrentUser: false },
      { emoji: '🤡', count: 7, reactedByCurrentUser: false },
    ],
    comments_count: 4,
    created_at: '2026-09-10T21:15:00Z',
    updated_at: '2026-09-10T21:15:00Z',
  },
  {
    id: 'clip-4',
    youtube_video_id: 'kJQP7kiw5Fk',
    youtube_url: 'https://www.youtube.com/watch?v=kJQP7kiw5Fk',
    title: 'Secret jump spot testing (Private test)',
    description: 'Testing bomb line-ups from kitchen to B site',
    thumbnail_url: 'https://img.youtube.com/vi/kJQP7kiw5Fk/hqdefault.jpg',
    game: 'Counter-Strike 2',
    category: 'Gaming',
    uploaded_by: 'user-darshan-1',
    uploader: {
      id: 'user-darshan-1',
      name: 'Darshan',
      avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
      email: 'darshan@example.com',
    },
    visibility: 'PRIVATE',
    tags: ['CS2', 'Nades', 'Lineups', 'Practice'],
    reactions: [],
    comments_count: 0,
    created_at: '2026-09-08T14:00:00Z',
    updated_at: '2026-09-08T14:00:00Z',
  },
];

export const INITIAL_MOCK_COMMENTS: Record<string, ClipComment[]> = {
  'clip-1': [
    {
      id: 'comm-1',
      clip_id: 'clip-1',
      user_id: 'user-rahul-2',
      user: {
        name: 'Rahul',
        email: 'rahul@example.com',
        avatar_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=120&auto=format&fit=crop&q=80',
      },
      content: 'WHAT THE FUCK WAS THAT BRAKING POINT BRO 😭😭',
      created_at: '2026-09-13T12:35:00Z',
      updated_at: '2026-09-13T12:35:00Z',
    },
    {
      id: 'comm-2',
      clip_id: 'clip-1',
      user_id: 'user-darshan-1',
      user: {
        name: 'Darshan',
        email: 'darshan@example.com',
        avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
      },
      content: 'Bro thought he was Verstappen into the wall 💀 my brakes overheated',
      created_at: '2026-09-13T12:40:00Z',
      updated_at: '2026-09-13T12:40:00Z',
    },
    {
      id: 'comm-3',
      clip_id: 'clip-1',
      user_id: 'user-akash-3',
      user: {
        name: 'Akash',
        email: 'akash@example.com',
        avatar_url: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=120&auto=format&fit=crop&q=80',
      },
      content: 'Certified Ferrari strategy moment',
      created_at: '2026-09-13T13:00:00Z',
      updated_at: '2026-09-13T13:00:00Z',
    },
  ],
  'clip-2': [
    {
      id: 'comm-4',
      clip_id: 'clip-2',
      user_id: 'user-darshan-1',
      user: {
        name: 'Darshan',
        email: 'darshan@example.com',
        avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=120&auto=format&fit=crop&q=80',
      },
      content: 'That flick onto catwalk was filthy',
      created_at: '2026-09-12T19:00:00Z',
      updated_at: '2026-09-12T19:00:00Z',
    },
  ],
};
